#pragma once

// Dispenser A
#define DISPENSER_A_REMOVAL_LED_PIN 22
#define DISPENSER_A_EMPTY_SWITCH_PIN 23
#define DISPENSER_A_MIN_LIMIT_SWITCH_PIN 24
#define DISPENSER_A_MAX_LIMIT_SWITCH_PIN 25
#define DISPENSER_A_MAX_LIMIT_SWITCH2_PIN 26
// Dispenser B
#define DISPENSER_B_REMOVAL_LED_PIN 32
#define DISPENSER_B_EMPTY_SWITCH_PIN 33
#define DISPENSER_B_MIN_LIMIT_SWITCH_PIN 34
#define DISPENSER_B_MAX_LIMIT_SWITCH_PIN 35
#define DISPENSER_B_MAX_LIMIT_SWITCH2_PIN 36
